apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - name: copy-config
        image: busybox:1.34
        command: ["sh", "-c", "cp /config/*.yaml /app/config/"]
        volumeMounts:
        - name: homepage-config
          mountPath: /config
        - name: live-config
          mountPath: /app/config
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "{{ host }},lab.{{ prod_host }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: live-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: live-config
          emptyDir: {}
        - name: logs
          emptyDir:
            {}
