apiVersion: v1
kind: Secret
metadata:
  name: langfuse-db-url
  namespace: langfuse
type: Opaque
stringData:
  url: postgres://langfuse:{{ postgres_langfuse_pass }}@langfuse-rw.cloudnative-pg.svc.cluster.local:5432/langfuse?sslmode=disable
  username: langfuse
  password: "{{ postgres_langfuse_pass }}"
