apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: langfuse
  namespace: langfuse
stringData:
  salt: "{{ langfuse_salt }}"
  encryption-key: "{{ langfuse_encryption_key }}"
  nextauth-secret: "{{ langfuse_nextauth_secret }}"
  postgresql-password: "{{ postgres_langfuse_pass }}"
  clickhouse-password: "{{ langfuse_clickhouse_pass }}"
  redis-password: "{{ langfuse_redis_pass }}"
  s3-access-key: "{{ langfuse_s3_access_key }}"
  s3-secret-key: "{{ langfuse_s3_secret_key }}"