apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- clusterrolebinding.yml
namespace: prod
patches:
  - path: configmap.yml
    target:
      name: homepage
      kind: ConfigMap