apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: coder-v2
type: Opaque
stringData:
  url: postgres://coder:{{ postgres_coder_pass }}@coder-rw.cloudnative-pg.svc.cluster.local:5432/coder?sslmode=disable
  username: coder
  password: {{ postgres_coder_pass }}

