csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=3
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

volumeSnapshotClasses: []

driver:
  config:
    driver: freenas-api-nfs
    instance_id: truenas
    httpConnection:
      protocol: https
      host: "{{ truenas_host }}"
      port: 443
      apiKey: "{{ truenas_api_key }}"
    zfs:
      datasetParentName: pool0/vostok/a/vols
      detachedSnapshotsDatasetParentName: pool0/vostok/a/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 1000
      datasetPermissionsGroup: 1000
    nfs:
      shareHost: "{{ truenas_host }}"
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: kubeuser
      shareMaprootGroup: kubeuser
      shareMapallUser: ""
      shareMapallGroup: ""