csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=3
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

volumeSnapshotClasses:
- name: freenas-nfs-snapshots

driver:
  config:
    driver: freenas-api-nfs
    instance_id: truenas
    httpConnection:
      protocol: https
      host: "{{ truenas_ip }}"
      port: 443
      apiKey: "{{ truenas_api_key }}"
      allowInsecure: true
    zfs:
      datasetParentName: main-pool/live/vostok/a/vols
      detachedSnapshotsDatasetParentName: main-pool/live/vostok/a/snaps
      datasetEnableQuotas: false
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 1000
      datasetPermissionsGroup: 1000
    nfs:
      shareHost: "{{ truenas_ip }}"
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: kubeuser
      shareMaprootGroup: kubeuser
      shareMapallUser: ""
      shareMapallGroup: ""

    _private:
      csi:
        volume:
          idTemplate: {% raw %} '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}' {% endraw %}
