apiVersion: v1
kind: Secret
metadata:
  name: paperless-db-url
type: Opaque
stringData:
  url: postgres://paperless:{{ postgres_paperless_pass }}@paperless-rw.cloudnative-pg.svc.cluster.local:5432/paperless?sslmode=disable
  username: paperless
  password: "{{ postgres_paperless_pass }}"
