apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: "{{ paperless_secret_key }}"
  PAPERLESS_ADMIN_USER: "{{ paperless_admin_user }}"
  PAPERLESS_ADMIN_PASSWORD: "{{ paperless_admin_pass }}"
  PAPERLESS_DBHOST: "paperless-rw.cloudnative-pg.svc.cluster.local"
  PAPERLESS_DBPASS: "{{ postgres_paperless_pass }}"
