apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  serviceName: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - containerPort: 9696
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
      - name: gluetun
        image: qmcgaw/gluetun:v3
        env:
        - name: VPN_SERVICE_PROVIDER
          value: surfshark
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: 10.0.0.0/8
        - name: DNS_PLAINTEXT_ADDRESS
          value: "10.43.0.10"
        envFrom:
        - secretRef:
            name: deluge-surfshark-creds
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: freenas-iscsi-csi
