apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
spec:
  storageClassName: ""
  volumeName: immich-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
