---
- name: Make sure the MariaDB container is created and running
  docker_container:
    name: "{{ container_name }}-mariadb"
    image: "mariadb:latest"
    pull: yes
    networks:
      - name: traefik-proxy
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb-read-only-compressed=OFF"
    state: 'started'
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"

      # Watchtower Update
      "com.centurylinklabs.watchtower.enable": "true"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "MYSQL_ROOT_PASSWORD": "{{ mysql_root_password }}"
      "MYSQL_DATABASE": "{{ mysql_db }}"
      "MYSQL_USER": "{{ mysql_user }}"
      "MYSQL_PASSWORD": "{{ mysql_etherpad_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/mariadb/mysql:/var/lib/mysql"
    restart_policy: unless-stopped

- name: Make sure the etherpad container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "etherpad/etherpad"
    pull: yes
    networks:
      - name: traefik-proxy
    state: 'started'
    env:
      "DB_TYPE": "mysql"
      "DB_HOST": "{{ container_name }}-mariadb"
      "DB_PORT": "3306"
      "DB_NAME": "{{ mysql_db }}"
      "DB_USER": "{{ mysql_user }}"
      "DB_PASS": "{{ mysql_etherpad_password }}"
      "DEFAULT_PAD_TEXT": "Your move — ♜"
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      "traefik.http.routers.etherpad.rule": "Host(`{{ subdomains[container_name] }}.{{ host }}`)"
      "traefik.http.services.etherpad.loadbalancer.server.port": "9001"

      "traefik.http.routers.etherpad.middlewares": "corsheader@file"
      
    restart_policy: unless-stopped