apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: dev-https-redirect@kubernetescrd
  name: coder-ingress
  namespace: coder
  labels:
    name: coder-ingress
spec:
  tls:
  - hosts:
    - "coder.{{ host }}"
    secretName: tenzing-dev-cert-tls
  defaultBackend:
    service:
      name: coder
      port:
        number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: coder
spec:
  redirectScheme:
    scheme: https
    permanent: true