---
- name: Make sure that the socket-proxy container is created and running
  docker_container:
    image: "tecnativa/docker-socket-proxy"
    name: "traefik-socket-proxy"
    pull: yes
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      "CONTAINERS": "1"
    networks:
      - name: traefik-proxy
    labels:
      # Watchtower Update
      "com.centurylinklabs.watchtower.enable": "true"


- name: Make sure that the traefik container is created and running
  docker_container:
    name: "traefik"
    image: "traefik:latest"
    pull: yes
    restart_policy: unless-stopped
    volumes:
     - "{{ docker_dir }}/traefik/traefik.yml:/traefik.yml:ro"
     - "{{ docker_dir }}/traefik/rules:/rules:ro"
     - "{{ docker_dir }}/swag/letsencrypt:/letsencrypt:ro"
    env:
      "CF_DNS_API_TOKEN": "{{ cloudflare_dns_token }}"
    published_ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    networks:
     - name: traefik-proxy
    labels:
      "traefik.enable": "true"

      # Watchtower Update
      "com.centurylinklabs.watchtower.enable": "true"
    