---
- name: Create the traefik conf folders
  file:
    path: "{{ docker_dir }}/traefik/"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create the traefik conf folders
  file:
    path: "{{ docker_dir }}/traefik/rules"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install the traefik config file
  template:
    src: "traefik.yml.j2"
    dest: "{{ docker_dir }}/traefik/traefik.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
