apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webUI.port }}
      targetPort: {{ .Values.service.webUI.targetPort }}
      protocol: TCP
      name: webui
    - port: {{ .Values.service.server.port }}
      targetPort: {{ .Values.service.server.targetPort }}
      protocol: TCP
      name: server
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
