---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    pull: yes
    networks:
      - name: traefik-proxy
    state: 'started'
    user: "{{ guid }}"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "DOCKER_USER": "{{ username }}"
    published_ports:
      - "8081:8080"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/test:/test"
    restart_policy: unless-stopped
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      "traefik.http.routers.{{app_name}}.rule": "Host(`{{app_name}}.{{ host }}`)"

      "traefik.http.routers.{{app_name}}.middlewares": "corsheader@file"