apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readarr
spec:
  selector:
    matchLabels:
      app: readarr
  serviceName: readarr
  replicas: 1
  template:
    metadata:
      labels:
        app: readarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: readarr
        image: lscr.io/linuxserver/readarr:0.3.18-develop
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - containerPort: 8787
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
        - mountPath: /data/media
          name: media
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: deluge-media-pvc
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: freenas-iscsi-csi
