apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: dev-https-redirect@kubernetescrd
  name: wazuh-dashboard-ingress
  namespace: wazuh
  labels:
    name: wazuh-dashboard-ingress
spec:
  rules:
  - host: "wazuh.{{ host }}"
    http:
      paths:
      - backend:
          service:
            name: dashboard
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "wazuh.{{ host }}"
    secretName: tenzing-dev-cert-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: wazuh
spec:
  redirectScheme:
    scheme: https
    permanent: true