---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: tdarr-media-pv
  storageClassName: ""
