---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: tdarr-media-pv
    volumeAttributes:
      server: "{{ truenas_ip }}"
      share: "/mnt/main-pool/live/baykal/media"
      node_attach_driver: nfs
      provisioner_driver: node-manual
