apiVersion: v1
kind: Service
metadata:
  name: "shelly-plug-monitor"
  labels:
    app: shelly-plug-monitor
spec:
  selector:
    app: "shelly-plug-monitor"
  ports:
  - name: stats
    port: 9080
    targetPort: stats