---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-store
  namespace: triton
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: freenas-nfs-csi