apiVersion: v1
kind: Secret
metadata:
  name: triton-minio-access-key
  namespace: triton
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ mlflow_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ mlflow_secret_access_key }}"
