---
- name: Make sure te {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "quay.io/minio/minio"
    command: "server /data --console-address ':9001'"
    pull: yes
    networks:
      - name: traefik-proxy
    state: 'started'
    env:
      "MINIO_ROOT_USER": "{{ minio_root_user }}"
      "MINIO_ROOT_PASSWORD": "{{ minio_root_password }}"
      "MINIO_BROWSER_REDIRECT_URL": "https://{{ container_name }}-console.{{ host }}"
    volumes:
      - "{{ mergerfs_root }}/{{ container_name }}/data:/data"
    restart_policy: unless-stopped
    expose:
      - "9000"
      - "9001"
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      # "traefik.http.routers.minio.rule": ""
      # "traefik.http.services.minio.loadbalancer.server.port": "9000"

      # "traefik.http.routers.minioconsole.rule": ""
      # "traefik.http.services.minioconsole.loadbalancer.server.port": "9001"

      "traefik.http.routers.minio.rule": "Host(`{{ container_name }}.{{ host }}`)"
      "traefik.http.routers.minio.entrypoints": "websecure"
      "traefik.http.routers.minio.service": "minio-service"
      "traefik.http.services.minio-service.loadbalancer.server.port": "9000"

      "traefik.http.routers.minioconsole.rule": "Host(`{{ container_name }}-console.{{ host }}`)"
      "traefik.http.routers.minioconsole.entrypoints": "websecure"
      "traefik.http.routers.minioconsole.service": "minio-console-service"
      "traefik.http.services.minio-console-service.loadbalancer.server.port": "9001"

