apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-config
type: Opaque
stringData:
  DOMAIN: "https://{{ subdomains['vaultwarden'] }}.{{ parent_host }}"
  YUBICO_CLIENT_ID: "{{ yubico_client_id }}"
  YUBICO_SECRET_KEY: "{{ yubico_secret_key }}"