apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: truecommand
spec:
  selector:
    matchLabels:
      app: truecommand
  serviceName: truecommand
  replicas: 1
  template:
    metadata:
      labels:
        app: truecommand
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: truecommand
        image: ixsystems/truecommand:3.0.1
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: freenas-iscsi-csi
