apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autotrim-pvc
  namespace: autotrim
spec:
  storageClassName: ""
  volumeName: autotrim-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
