---
- name: Clone the latest dotfiles repo
  become: no
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dotfiles"
    recursive: no
    force: yes

- name: Stow the dotfiles
  become: no
  shell:
    cmd: ./install
    chdir: "/home/{{ username }}/dotfiles"
  register: dotbot_result
  changed_when: dotbot_result.stdout != ""
  failed_when: dotbot_result.rc not in [0, 1]
