apiVersion: v1
kind: Service
metadata:
  name: "minio"
spec:
  selector:
    app: "minio"
  ports:
    - port: 9090
      targetPort: web
      name: web
    - port: 9000
      targetPort: api
      name: api