apiVersion: v1
kind: Service
metadata:
  name: "openspeedtest"
spec:
  selector:
    app: "openspeedtest"
  ports:
    - port: 3000
      targetPort: http
      name: http
    - port: 3001
      targetPort: https
      name: https
