{
 "title": "Power monitoring (Shelly)",
 "description": "Smartplug power monitoring",
 "tags": [
  "fleet",
  "power",
  "shelly"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "currency", "label": "Currency", "query": "EUR : 0.3, INR : 8" },
   { "name": "device_id", "label": "Device ID", "query": { "query": "smartplug_power_watts" } },
   {
    "name": "device_name",
    "label": "Device name",
    "query": {
     "query": "smartplug_power_watts{device_id=\"$device_id\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated monthly cost (${currency:text})",
   "type": "stat",
   "description": "Estimated energy cost based on last week's usage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$currency * 4 * (increase(smartplug_energy_watthour_total{device_id=\"$device_id\"}[7d]) / 1000)"
    }
   ]
  },
  {
   "title": "Energy usage (7d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smartplug_energy_watthour_total{device_id=\"$device_id\"}[7d]) / 1000"
    }
   ]
  },
  {
   "title": "Energy usage (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smartplug_energy_watthour_total{device_id=\"$device_id\"}[24h]) / 1000"
    }
   ]
  },
  {
   "title": "Energy usage (time range)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smartplug_energy_watthour_total{device_id=\"$device_id\"}[$__range]) / 1000"
    }
   ]
  },
  {
   "title": "Instantaneous power",
   "type": "stat",
   "description": "Current power",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartplug_power_watts{device_id=\"$device_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage fluctuation",
   "type": "stat",
   "description": "Difference between min and max voltage",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(smartplug_voltage_volts{device_id=\"$device_id\"}[$__range]) - min_over_time(smartplug_voltage_volts{device_id=\"$device_id\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last outage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(timestamp(absent_over_time(smartplug_voltage_volts[1m]))) * 1000",
     "legendFormat": "Started"
    },
    {
     "expr": "delta(timestamp(absent_over_time(smartplug_voltage_volts[1m]))[$__range:1m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "smartplug_power_watts{device_id=\"$device_id\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "smartplug_current_amps{device_id=\"$device_id\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "smartplug_voltage_volts{device_id=\"$device_id\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartplug_temperature_celcius{device_id=\"0\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}