apiVersion: v1
kind: Service
metadata:
  name: "csgo-dedicated-server"
spec:
  type: NodePort
  selector:
    app: "csgo-dedicated-server"
  ports:
    - targetPort: tcp-01
      name: tcp-01
      port: 27015
    - targetPort: tcp-02
      name: tcp-02
      port: 27036
    - targetPort: udp-02
      name: udp-02
      port: 27020
    - targetPort: udp-03
      name: udp-03
      port: 27031
    - targetPort: udp-04
      name: udp-04
      port: 27032
    - targetPort: udp-05
      name: udp-05
      port: 27033
    - targetPort: udp-06
      name: udp-06
      port: 27034
    - targetPort: udp-07
      name: udp-07
      port: 27035