apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: dev-https-redirect@kubernetescrd
  name: main-ingress
  labels:
    name: main-ingress
spec:
  tls:
  - hosts:
    - "{{ host }}"
    - "*.{{ host }}"
    secretName: tenzing-dev-cert-tls
  defaultBackend:
    service:
      name: heimdall
      port:
        number: 80
  rules:
  - host: "{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: homepage
            port: 
              number: 3000
  - host: "homeassistant.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: home-assistant
            port: 
              number: 80
  - host: "docker-registry.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: docker-registry
            port: 
              number: 5000
  - host: "vault.{{ parent_host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vaultwarden
            port: 
              number: 80
  - host: "mlflow.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mlflow
            port: 
              number: 5000
  - host: "minio.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9090
  - host: "minio-api.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9000
  - host: "deluge.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deluge
            port: 
              number: 8112
  - host: "radarr.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: radarr
            port: 
              number: 7878
  - host: "prowlarr.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prowlarr
            port: 
              number: 9696
  - host: "sonarr.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sonarr
            port: 
              number: 8989
  - host: "shell.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ttyd
            port: 
              number: 7681
  - host: "readarr.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: readarr
            port: 
              number: 8787
  - host: "kavita.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kavita
            port: 
              number: 5000
  - host: "truecommand.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: truecommand
            port: 
              number: 80
  - host: "paperless.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: paperless-ngx
            port: 
              number: 8000
  - host: "linkwarden.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: linkwarden
            port: 
              number: 3000
  - host: "obsidian-couchdb.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: obsidian-couchdb
            port: 
              number: 5984
  - host: "crafty.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: crafty
            port: 
              number: 8443
  - host: "speedtest.{{ host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: openspeedtest
            port: 
              number: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: dev
spec:
  redirectScheme:
    scheme: https
    permanent: true