---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: cloudnative-pg
type: Opaque
stringData:
  ACCESS_KEY_ID: "{{ cnpg_backup_key_id }}"
  ACCESS_SECRET_KEY: "{{ cnpg_backup_secret_key }}"