apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  # settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  bookmarks.yaml: |
    - General:
        - WindowSwap:
            - abbr: WS
              href: https://www.window-swap.com/Window
  services.yaml: |
    - Infrastructure:
        - Proxmox:
            href: https://phoenix.artemis.{{ parent_host }}
            icon: proxmox.png
            description: VM cluster
            widget:
              type: proxmox
              url: https://phoenix.artemis.{{ parent_host }}
              username: {{ proxmox_api_username }}
              password: {{ proxmox_api_token }}
        - Portainer:
            href: https://portainer.artemis.{{ parent_host }}
            icon: portainer.png
            description: Docker containers on DigitalOcean droplet
            widget:
              type: portainer
              url: https://{{ artemis_tailscale_ip }}:9443
              env: 2
              key: {{ portainer_api_token }}
        - TrueNAS:
            href: https://{{ truenas_host }}
            icon: truenas.png
            description: NAS
            widget:
              type: truenas
              url: https://{{ truenas_host }}
              key: {{ truenas_api_key }}
        - Omada:
            href: https://omada.{{ parent_host }}
            icon: omada.png
            description: Networking infra
            widget:
              type: omada
              url: https://omada.{{ parent_host }}
              username: {{ omada_user_name }}
              password: {{ omada_user_pass }}
              site: Homelab
              fields: ["activeUser", "alerts", "connectedGateways"]

    - Services:
        - Nextcloud:
            href: https://nextcloud.{{ host }}
            ping: https://nextcloud.{{ host }}/status.php
            description: File sharing
            icon: nextcloud.png
        - Bitwarden:
            href: https://vault.{{ parent_host }}
            ping: https://vault.{{ parent_host }}
            description: Password manager
            icon: bitwarden.png
        - MLFlow:
            href: https://mlflow.{{ host }}
            ping: https://mlflow.{{ host }}
            description: ML experiment and model organization
            icon: https://mlflow.{{ host }}/static-files/favicon.ico
        - Argo CD:
            href: https://argocd.{{ host }}
            ping: https://argocd.{{ host }}
            description: Continuous Deployment
            icon: argocd.png
        - Coder:
            href: https://coder.{{ host }}
            ping: https://coder.{{ host }}
            description: Remote dev
            icon: coder.png
        - Label Studio:
            href: https://labelstudio.{{ host }}
            ping: https://labelstudio.{{ host }}
            description: Annotation and labelling project organization
            icon: https://labelstudio.{{ host }}/favicon.ico
        - MinIO:
            href: https://minio.{{ host }}
            ping: https://minio.{{ host }}
            description: Object storage
            icon: minio.png

    - Media:
        - Jellyfin:
            href: https://media.{{ parent_host }}
            ping: http://{{ jellyfin_tailscale_ip }}:8096/health
            description: Media streaming
            icon: jellyfin.png
            widget:
              type: jellyfin
              url: http://{{ jellyfin_tailscale_ip }}:8096
              key: {{ jellyfin_api_key }}
              enableBlocks: true
        - Radarr:
            href: https://radarr.{{ host }}
            ping: https://radarr.{{ host }}
            description: Movie library management
            icon: radarr.png
            widget:
              type: radarr
              url: https://radarr.{{ host }}
              key: {{ radarr_api_key }}
        - Deluge:
            href: https://deluge.{{ host }}
            ping: https://deluge.{{ host }}
            description: Download manager
            icon: deluge.png
            widget:
              type: deluge
              url: https://deluge.{{ host }}
              password: {{ deluge_webui_password }}

    - Observability:
        - Uptime Kuma:
            href: https://status.{{ parent_host }}
            icon: uptime-kuma.png
            description: Service uptime
            widget:
              type: uptimekuma
              url: https://status.{{ parent_host }}
              slug: overall
        - Netdata:
            href: https://app.netdata.cloud/spaces/shikharbhardwa-space/rooms/all-nodes/home
            icon: netdata.png
            description: Hardware monitoring
        - Grafana:
            href: https://arete.grafana.net
            icon: grafana.png
            description: Application stats and logs
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster: tenzing"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
    - openmeteo:
        label: Delhi
        latitude: 28.7
        longitude: 77.1
        timezone: Asia/Kolkata
        units: metric
        cache: 5
  docker.yaml: ""