---
- name: Create the site folder
  file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "site"
- name: Copy the site contents
  ansible.builtin.copy:
    src: blog
    dest: "{{ docker_dir }}/{{ container_name }}"