---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    pull: yes
    networks:
      - name: traefik-proxy
    state: 'started'
    user: "{{ guid }}"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "DOCKER_USER": "{{ username }}"
    command:
      - server
    published_ports:
      - "1313:1313"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/blog:/src"
    restart_policy: unless-stopped
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      "traefik.http.routers.hugo.rule": "Host(`{{ host }}`)"

      "traefik.http.routers.hugo.middlewares": "corsheader@file"