---

- name: Create the configuration directory
  become: true
  file:
    path: "{{ docker_dir }}/{{ container_name }}/conf"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install the configuration template
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/conf/configuration.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  notify:
    - Restart the docker container

- name: Install the users template
  template:
    src: users_database.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/conf/users_database.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  register: users