---
- name: Create the codeserver folders
  file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "project"
    - "config"
- name: Make sure the code-server container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "codercom/code-server:latest"
    pull: yes
    networks:
      - name: traefik-proxy
    state: 'started'
    user: "{{ guid }}"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "DOCKER_USER": "{{ username }}"
    published_ports:
      - "8081:8080"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/home/coder/.config"
      - "{{ docker_dir }}/{{ container_name }}/project:/home/coder/project"
    restart_policy: unless-stopped
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      "traefik.http.routers.codeserver.rule": "Host(`code.{{ host }}`)"

      "traefik.http.routers.codeserver.middlewares": "corsheader@file"