apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    email: "{{ letsencrypt_email }}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dev
    solvers:
    - dns01:
        cloudflare:
          email: "{{ letsencrypt_email }}"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token