http:
  routers:
    phoenix:
      rule: "Host(`phoenix.{{ oci_host }}`)"
      entryPoints:
        - websecure
      service: phoenix
      tls:
        certResolver: cloudflare

    media:
      rule: "Host(`media.{{ oci_parent_host }}`)"
      entryPoints:
        - websecure
      service: media
      tls:
        certResolver: cloudflare

    photos:
      rule: "Host(`photos.{{ oci_parent_host }}`)"
      entryPoints:
        - websecure
      service: photos
      tls:
        certResolver: cloudflare

  services:
    phoenix:
      loadBalancer:
        servers:
          - url: "https://{{ thor_tailscale_ip }}:8006"
        serversTransport: insecure-transport
    media:
      loadBalancer:
        servers:
          - url: "http://{{ jellyfin_tailscale_ip }}:8096"
    photos:
      loadBalancer:
        servers:
          - url: "https://immich.{{ tenzing_host }}"


  serversTransports:
    insecure-transport:
      insecureSkipVerify: true