http:
  routers:
    phoenix:
      rule: "Host(`phoenix.{{ oci_host }}`)"
      entryPoints:
        - websecure
      service: phoenix
      tls:
        certResolver: cloudflare

    media:
      rule: "Host(`media.{{ oci_parent_host }}`)"
      entryPoints:
        - websecure
      service: media
      tls:
        certResolver: cloudflare

    photos:
      rule: "Host(`photos.{{ oci_parent_host }}`)"
      entryPoints:
        - websecure
      service: photos
      tls:
        certResolver: cloudflare

    speedtest:
      rule: "Host(`speedtest.{{ oci_host }}`)"
      entryPoints:
        - websecure
      service: speedtest
      tls:
        certResolver: cloudflare

    drive:
      rule: "Host(`drive.{{ oci_parent_host }}`)"
      entryPoints:
        - websecure
      service: drive
      tls:
        certResolver: cloudflare

  services:
    phoenix:
      loadBalancer:
        servers:
          - url: "https://{{ thor_tailscale_ip }}:8006"
        serversTransport: insecure-transport
    media:
      loadBalancer:
        servers:
          - url: "http://{{ jellyfin_tailscale_ip }}:8096"
    photos:
      loadBalancer:
        servers:
          - url: "https://immich.{{ tenzing_host }}"
        serversTransport: photos-transport

    speedtest:
      loadBalancer:
        servers:
          - url: "https://speedtest.{{ tenzing_host }}"
    drive:
      loadBalancer:
        servers:
          - url: "https://drive.{{ tenzing_host }}"

  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
    photos-transport:
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 0
        readIdleTimeout: 3600s

