apiVersion: v1
kind: Secret
metadata:
  name: csgo-dedicated-server-env
type: Opaque
stringData:
  SRCDS_HOSTNAME: "{{ csgo_server_hostname }}"
  SRCDS_PW: "{{ csgo_server_password }}"
  SRCDS_RCONPW: "{{ csgo_rcon_password }}"
  SRCDS_TOKEN: "{{ csgo_game_login_token }}"
  SRCDS_WORKSHOP_AUTHKEY: "{{ csgo_api_authkey }}"
  SOURCEMOD_ADMINS: "{{ csgo_server_admins }}"
