apiVersion: v1
kind: Secret
metadata:
  name: liftbook-staging-db-url
type: Opaque
stringData:
  url: postgres://liftbook-staging:{{ postgres_liftbook_staging_pass }}@liftbook-staging-rw.cloudnative-pg.svc.cluster.local:5432/liftbook_staging?sslmode=disable
  username: liftbook-staging
  password: "{{ postgres_liftbook_staging_pass }}"
