apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: dev-https-redirect@kubernetescrd
  name: label-studio-ingress
  namespace: label-studio
  labels:
    name: label-studio-ingress
spec:
  rules:
  - host: labelstudio.{{ host }}
    http:
      paths:
      - backend:
          service:
            name: label-studio-ls-app
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "labelstudio.{{ host }}"
    secretName: tenzing-dev-cert-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: label-studio
spec:
  redirectScheme:
    scheme: https
    permanent: true