apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: dev-https-redirect@kubernetescrd
  name: nextcloud-ingress
  namespace: nextcloud
  labels:
    name: nextcloud-ingress
spec:
  rules:
  - host: nextcloud.{{ host }}
    http:
      paths:
      - backend:
          service:
            name: nextcloud
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "nextcloud.{{ host }}"
    secretName: tenzing-dev-cert-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: nextcloud
spec:
  redirectScheme:
    scheme: https
    permanent: true