---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "home-assistant"
spec:
  selector:
    matchLabels:
      app: "home-assistant"
  serviceName: "home-assistant"
  replicas: 1
  template:
    metadata:
      labels:
        app: "home-assistant"
    spec:
      containers:
      - name: "home-assistant"
        image: "ghcr.io/home-assistant/home-assistant:stable"
        ports:
        - containerPort: 8123
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
