apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "minio"
spec:
  selector:
    matchLabels:
      app: "minio"
  serviceName: "minio"
  template:
    metadata:
      labels:
        app: "minio"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: "minio"
        image: "quay.io/minio/minio:latest"
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        ports:
          - containerPort: 9090
            name: web
          - containerPort: 9000
            name: api
        envFrom:
          - secretRef:
              name: minio-admin-creds
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/data"
            name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: freenas-nfs-csi
