---
- name: Make the data directory for Victoriametrics
  file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "victoriametrics/data"
    - "etc"
    - "prometheus"

- name: Install the prometheus config
  template:
    src: "prometheus.yml.j2"
    dest: "{{ docker_dir }}/{{ container_name }}/etc/prometheus.yml"
