apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-media-pvc
spec:
  storageClassName: ""
  volumeName: deluge-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
