apiVersion: v1
kind: Service
metadata:
  name: "deluge"
spec:
  selector:
    app: "deluge"
  ports:
  - name: webui
    port: 8112
    targetPort: 8112
    protocol: TCP
  - name: torrent-tcp
    port: 6881
    targetPort: 6881
    protocol: TCP
  - name: torrent-udp
    port: 6881
    targetPort: 6881
    protocol: UDP