apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: omada-exporter
spec:
  selector:
    matchLabels:
      app: omada-exporter
  endpoints:
  - port: metrics
    path: /metrics