apiVersion: v1
kind: Service
metadata:
  name: "omada-exporter"
  labels:
    app: "omada-exporter"
spec:
  selector:
    app: "omada-exporter"
  ports:
  - name: "metrics"
    port: 9202
    targetPort: 9202