apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-db-url
type: Opaque
stringData:
  url: postgres://linkwarden:{{ postgres_linkwarden_pass }}@linkwarden-rw.cloudnative-pg.svc.cluster.local:5432/linkwarden?sslmode=disable
  username: linkwarden
  password: "{{ postgres_linkwarden_pass }}"
