apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-env
type: Opaque
stringData:
  NEXTAUTH_SECRET: "{{ linkwarden_nextauth_secret }}"
  NEXTAUTH_URL: "https://linkwarden.{{ host }}/api/v1/auth"
