name: CD

on:
  push:
    branches: [ main, add-cd-for-kustomize ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Kubeconfig and Certs
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/out/deploy.kubeconfig

      - name: Deploy
        env:
            ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
            KUBECONFIG: ${{ github.workspace }}/out/deploy.kubeconfig
        run: |
            ./deployment/automation/deploy.sh 
            
          
