apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crafty-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`crafty.{{ host }}`)
      kind: Rule
      services:
        - name: crafty
          port: 8443
          serversTransport: insecure-transport
