apiVersion: v1
kind: Service
metadata:
  name: "crafty"
spec:
  selector:
    app: "crafty"
  ports:
    - port: 8123
      targetPort: web
      name: web
    - port: 8443
      targetPort: websecure
      name: websecure
    - port: 19132
      targetPort: bedrock
      protocol: UDP
      name: bedrock
