---

- name: Create the sqlite db file
  file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "sqlite"

- name: Make sure the Rustpad container is created and running.
  docker_container:
    name: "{{ container_name }}"
    image: "ekzhang/rustpad"
    networks:
      - name: traefik-proxy
    pull: true
    state: 'started'
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "traefik-proxy"

      "traefik.http.routers.rustpad.rule": "Host(`{{ subdomains[container_name] }}.{{ host }}`)"
      "traefik.http.services.rustpad.loadbalancer.server.port": "3030"

      "traefik.http.routers.rustpad.middlewares": "corsheader@file"
    env:
      EXPIRY_DAYS: "7"
      SQLITE_URI: "sqlite:///data/sqlite/sqlite.db"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
    restart_policy: unless-stopped